repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: openfaas
    url: https://openfaas.github.io/faas-netes/
  - name: jetstack
    url: https://charts.jetstack.io
helmDefaults:
  tillerNamespace: kube-system
  tillerless: false
  wait: false
  verify: false
releases:
  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
  - name: cert-manager-issuers
    namespace: cert-manager
    chart: cert-manager/cert-manager-issuers
  - name: nginx-ingress
    namespace: ingress-nginx
    chart: stable/nginx-ingress
  - name: openfaas
    namespace: openfaas
    chart: openfaas/openfaas
    values:
      - "./openfaas/values.yaml"
  - name: monitor-ingress
    namespace: monitoring
    chart: monitor-ingress
    verify: false
    values:
      - "./monitor-ingress/values.yaml"
      - github:
          OAUTH2_PROXY_CLIENT_ID: {{ requiredEnv "GITHUB_CLIENT_ID" }}
          OAUTH2_PROXY_CLIENT_SECRET: {{ requiredEnv "GITHUB_CLIENT_SECRET" }}
  - name: prometheus
    chart: stable/prometheus-operator
    namespace: monitoring
    version: ~5
    verify: false
    values:
      - "./prometheus-operator/values.yaml"
  - name: openfaas-monitoring
    namespace: openfaas
    chart: openfaas-monitoring
    verify: false
    values:
      - "./openfaas-monitoring/Values.yml"