{
 "title": "Original Open FaaS Dashboard",
 "description": "OpenFaaS dashboard with autoscaling",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Function rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gateway_function_invocation_total[1m])",
     "legendFormat": "{{ function_name }} {{code}}"
    }
   ]
  },
  {
   "title": "Replica scaling",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gateway_service_count", "legendFormat": "{{function_name}} " }
   ]
  },
  {
   "title": "Total requests - 200 OK",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "scalar( sum( gateway_function_invocation_total {  code=\"200\"} ))"
    }
   ]
  },
  {
   "title": "Execution duration (s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(rate(gateway_functions_seconds_sum[5m]) / rate(gateway_functions_seconds_count[5m]))",
     "legendFormat": "{{function_name}} "
    }
   ]
  }
 ]
}