apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secrets
type: Opaque
data:
  clientId: {{ .Values.github.OAUTH2_PROXY_CLIENT_ID | b64enc | quote }}
  clientSecret: {{ .Values.github.OAUTH2_PROXY_CLIENT_SECRET | b64enc | quote }}
  cookieSecret: N7sFr63pL1jnMK21G98Kag==