prometheus:
  ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        nginx.ingress.kubernetes.io/auth-url: "https://monitor.helm-notifier.com/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://monitor.helm-notifier.com/oauth2/start"
    tls:
      - secretName: letsencrypt-prod
        hosts:
          - monitor.helm-notifier.com
    hosts:
      - monitor.helm-notifier.com
    paths:
      - /prometheus/?(.*)
  prometheusSpec:
    externalUrl: https://monitor.helm-notifier.com/prometheus/
    ruleNamespaceSelector:
      any: true
      matchNames: []
    serviceMonitorNamespaceSelector:
      any: true
      matchNames: []
alertmanager:
  ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        nginx.ingress.kubernetes.io/auth-url: "https://monitor.helm-notifier.com/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://monitor.helm-notifier.com/oauth2/start"
    tls:
      - secretName: letsencrypt-prod
        hosts:
          - monitor.helm-notifier.com
    hosts:
      - monitor.helm-notifier.com
    paths:
      - /alertmanager/?(.*)
  alertmanagerSpec:
    externalUrl: https://monitor.helm-notifier.com/alertmanager/
  config:
    route:
      group_by: [alertname, job]
      receiver: default
grafana:
  sidecar:
    dashboards:
      searchNamespace: ALL
  ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        nginx.ingress.kubernetes.io/auth-url: "https://monitor.helm-notifier.com/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://monitor.helm-notifier.com/oauth2/start"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          set_by_lua $user 'return ngx.decode_base64(string.gsub(ngx.var.cookie__oauth2_proxy,"(%w+)|.+", "%1"))';
          proxy_set_header X-WEBAUTH-USER $user;
    hosts:
      - monitor.helm-notifier.com
    path: /grafana/?(.*)
    tls:
      - secretName: letsencrypt-prod
        hosts:
          - monitor.helm-notifier.com
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana/"
    users:
      auto_assign_org: true
      auto_assign_org_role: Editor
    auth:
      disable_login_form: true
      disable_signout_menu: true
    auth.proxy:
      enabled: true
  image:
    tag: 6.2.4