repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: openfaas
    url: https://openfaas.github.io/faas-netes/
  - name: jetstack
    url: https://charts.jetstack.io
helmDefaults:
  tillerNamespace: kube-system
  tillerless: false
  wait: false
  verify: false
releases:
  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    version: v0.11.0
  - name: nginx-ingress
    namespace: ingress-nginx
    chart: stable/nginx-ingress
    version: 1.24.4
    values:
      - "../charts/nginx-ingress/values.yaml"
  - name: openfaas
    namespace: openfaas
    chart: openfaas/openfaas
    version: 5.2.1
    values:
      - "../charts/openfaas/values.yaml"
  - name: prometheus
    chart: stable/prometheus-operator
    namespace: monitoring
    version: 6.21.0
    verify: false
    values:
      - "../charts/prometheus-operator/values.yaml"
  - name: monitor-ingress
    namespace: monitoring
    chart: ../charts/monitor-ingress
    verify: false
    values:
      - "../charts/monitor-ingress/values.yaml"
      - github:
          OAUTH2_PROXY_CLIENT_ID: {{ requiredEnv "GITHUB_CLIENT_ID" }}
          OAUTH2_PROXY_CLIENT_SECRET: {{ requiredEnv "GITHUB_CLIENT_SECRET" }}
  - name: cert-manager-issuers
    namespace: cert-manager
    chart: ../charts/cert-manager-issuers